name: CI

on:
  push:
    branches:
      - master
      - 'v*' # older version branches
    tags:
      - '*'
  pull_request: {}
  schedule:
    - cron: '0 6 * * 0' # weekly, on sundays

jobs:
  test:
    timeout-minutes: 5
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['16', '18']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 7
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm prepare
      - run: pnpm lint
      - run: pnpm test
